class Commissions {

    commissions = [
        {
            id: 0,
            antCountRequirement: 750,
            payment: 500000,
            letterContents: "Here at the Gristhorpe Gallery we've been blown away by the quality of paintings coming from your studio. We would like to commission a piece for our gallery",
            paymentLetterContents: "Thank you for your wonderful painting. It is just as stunning as I imagined.",
            paintingContent: "a bowl of apples",
            director: "Simon Wixon",
            galleryWallColour: new Color(89, 222, 220),
            paintingType: 0
        },
        {
            id: 1,
            antCountRequirement: 1090,
            payment: 1000000,
            letterContents: "We've been following your work for a while here at the Irving Gallery, and we're very impressed! We want to commission a painting.",
            paymentLetterContents: "What an incredible painting! We couldn't have asked for anything better!",
            paintingContent: "a woman in a red dress",
            director: "Ellie Keys",
            galleryWallColour: new Color(125, 222, 89),
            paintingType: 0
        },
        {
            id: 2,
            antCountRequirement: 1430,
            payment: 1500000,
            letterContents: "I'm the director of the Warwards Gallery, and we're looking to commission some new groundbreaking art pieces.",
            paymentLetterContents: "We could not be happier with your painting, our visitor numbers have already increased since displaying it!",
            paintingContent: "a snail that doesn't look like a snail",
            director: "Max Brown",
            galleryWallColour: new Color(222, 89, 119),
            paintingType: 0
        },
        {
            id: 3,
            antCountRequirement: 1770,
            payment: 2000000,
            letterContents: "We need some new paintings at Ford Street Gallery, and we simply must have one of yours!",
            paymentLetterContents: "Wow, what an incredible painting! Christmas came early this year",
            paintingContent: "a red toadstool",
            director: "Alice Wilson",
            galleryWallColour: new Color(151, 222, 89),
            paintingType: 0
        },
        {
            id: 4,
            antCountRequirement: 2110,
            payment: 2500000,
            letterContents: "Your paintings are all that anyone can talk about! We'd love to commission a piece for the Grosvenor Gallery",
            paymentLetterContents: "We are extremely satisfied with the quality and content of the painting that you sent us",
            paintingContent: "misty mountains at sunset",
            director: "Sam Russell",
            galleryWallColour: new Color(89, 222, 191),
            paintingType: 0
        },
        {
            id: 5,
            antCountRequirement: 2450,
            payment: 3000000,
            letterContents: "Your unique art style is a must-have! Please send one of your many masterpieces to Columbine Gallery",
            paymentLetterContents: "Glorious, this one will surely gather a stupendous crowd!",
            paintingContent: "a face with offset features",
            director: "Peter Dickson",
            galleryWallColour: new Color(200, 89, 222),
            paintingType: 1
        },
        {
            id: 6,
            antCountRequirement: 2790,
            payment: 3500000,
            letterContents: "The prestigious Windmill Gallery has demanded that I acquire one of your contemporary art works on their behalf, please may I commission a painting?",
            paymentLetterContents: "When your painting arrived it brought a tear to our eyes! We can't thank you enough",
            paintingContent: "a sad man at the beach",
            director: "Becky Ward-Morris",
            galleryWallColour: new Color(89, 222, 182),
            paintingType: 1
        },
        {
            id: 7,
            antCountRequirement: 3130,
            payment: 4000000,
            letterContents: "Bold, vibrant, brilliant! That's how the Lavender Gallery (who want to commission one of your paintings) describe you!",
            paymentLetterContents: "Your bespoke artwork has arrived, and I must say, BRAVO!",
            paintingContent: "ballerinas",
            director: "Lanre Bamisaye",
            galleryWallColour: new Color(148, 89, 222),
            paintingType: 1
        },
        {
            id: 8,
            antCountRequirement: 3470,
            payment: 4500000,
            letterContents: "The paintings you create are truly one-of-a-kind! We, the Georgehill Gallery, must have one!",
            paymentLetterContents: "A true visionary! Such amazing brushwork! It was a pleasure doing business with you",
            paintingContent: "an island at sunset",
            director: "Becky Wixon",
            galleryWallColour: new Color(89, 222, 125),
            paintingType: 1
        },
        {
            id: 9,
            antCountRequirement: 3810,
            payment: 5000000,
            letterContents: "There is an empty space at Primrose Gallery, which can only be filled by an incredible visionary such as yourself. Please allow us to procure a painting from you!",
            paymentLetterContents: "This is truly a one of a kind piece, consider us more than satisfied!",
            paintingContent: "farmers outside their house",
            director: "Sam Nash",
            galleryWallColour: new Color(189, 222, 89),
            paintingType: 2
        },
        {
            id: 10,
            antCountRequirement: 4150,
            payment: 5500000,
            letterContents: "Here at the Strichley Gallery we've been blown away by the quality of paintings coming from your studio. We would like to commission a piece for our gallery",
            paymentLetterContents: "Thank you for your wonderful painting. It is just as stunning as I imagined.",
            paintingContent: "a man swimming in a pool",
            director: "Jordy Williams",
            galleryWallColour: new Color(202, 222, 89),
            paintingType: 1
        },
        {
            id: 11,
            antCountRequirement: 4490,
            payment: 6000000,
            letterContents: "We've been following your work for a while here at the Harbourne Gallery, and we're very impressed! We want to commission a painting.",
            paymentLetterContents: "What an incredible painting! We couldn't have asked for anything better!",
            paintingContent: "a woman dreaming",
            director: "Beth Dolphin",
            galleryWallColour: new Color(222, 89, 173),
            paintingType: 2
        },
        {
            id: 12,
            antCountRequirement: 4830,
            payment: 6500000,
            letterContents: "I'm the director of the Selly Gallery, and we're looking to commission some new groundbreaking art pieces.",
            paymentLetterContents: "We could not be happier with your painting, our visitor numbers have already increased since displaying it!",
            paintingContent: "human fear of darkness",
            director: "James Double",
            galleryWallColour: new Color(89, 222, 222),
            paintingType: 2
        },
        {
            id: 13,
            antCountRequirement: 5170,
            payment: 7000000,
            letterContents: "We need some new paintings at Cherrington Gallery, and we simply must have one of yours!",
            paymentLetterContents: "Wow, what an incredible painting! Christmas came early this year",
            paintingContent: "a girl with pearl earrings",
            director: "Zara Tappy",
            galleryWallColour: new Color(222, 89, 147),
            paintingType: 3
        },
        {
            id: 14,
            antCountRequirement: 5510,
            payment: 7500000,
            letterContents: "Your paintings are all that anyone can talk about! We'd love to commission a piece for the Umberslade Gallery",
            paymentLetterContents: "We are extremely satisfied with the quality and content of the painting that you sent us",
            paintingContent: "a forest",
            director: "Jack Houghton",
            galleryWallColour: new Color(220, 89, 222),
            paintingType: 2
        },
        {
            id: 15,
            antCountRequirement: 5850,
            payment: 8000000,
            letterContents: "Your unique art style is a must-have! Please send one of your many masterpieces to Pershore Gallery",
            paymentLetterContents: "Glorious, this one will surely gather a stupendous crowd!",
            paintingContent: "a group at the park",
            director: "Katie Bennett",
            galleryWallColour: new Color(222, 196, 89),
            paintingType: 3
        },
        {
            id: 16,
            antCountRequirement: 6190,
            payment: 8500000,
            letterContents: "The prestigious Brandwood Gallery has demanded that I acquire one of your contemporary art works on their behalf, please may I commission a painting?",
            paymentLetterContents: "When your painting arrived it brought a tear to our eyes! We can't thank you enough",
            paintingContent: "sunflowers",
            director: "Tom Lancaster",
            galleryWallColour: new Color(180, 89, 222),
            paintingType: 2
        },
        {
            id: 17,
            antCountRequirement: 6530,
            payment: 9000000,
            letterContents: "Bold, vibrant, brilliant! That's how the Broad Meadow Gallery (who want to commission one of your paintings) describe you!",
            paymentLetterContents: "Your bespoke artwork has arrived, and I must say, BRAVO!",
            paintingContent: "the sky in an eye",
            director: "Beth Harisson",
            galleryWallColour: new Color(198, 89, 222),
            paintingType: 3
        },
        {
            id: 18,
            antCountRequirement: 6870,
            payment: 9500000,
            letterContents: "The paintings you create are truly one-of-a-kind! We, the Hawkesley Gallery, must have one!",
            paymentLetterContents: "A true visionary! Such amazing brushwork! It was a pleasure doing business with you",
            paintingContent: "a boat made out of the sea",
            director: "Callum Rose",
            galleryWallColour: new Color(163, 222, 89),
            paintingType: 4
        },
        {
            id: 19,
            antCountRequirement: 7210,
            payment: 10000000,
            letterContents: "There is an empty space at Longbridge Gallery, which can only be filled by an incredible visionary such as yourself. Please allow us to procure a painting from you!",
            paymentLetterContents: "This is truly a one of a kind piece, consider us more than satisfied!",
            paintingContent: "three grazing horses",
            director: "Donald Skunk",
            galleryWallColour: new Color(222, 89, 151),
            paintingType: 3
        },
        {
            id: 20,
            antCountRequirement: 7550,
            payment: 10500000,
            letterContents: "Here at the Gerrards Gallery we've been blown away by the quality of paintings coming from your studio. We would like to commission a piece for our gallery",
            paymentLetterContents: "Thank you for your wonderful painting. It is just as stunning as I imagined.",
            paintingContent: "a tree",
            director: "Monty Bewicke",
            galleryWallColour: new Color(222, 89, 188),
            paintingType: 4
        },
        {
            id: 21,
            antCountRequirement: 7890,
            payment: 11000000,
            letterContents: "We've been following your work for a while here at the Chalfont Gallery, and we're very impressed! We want to commission a painting.",
            paymentLetterContents: "What an incredible painting! We couldn't have asked for anything better!",
            paintingContent: "a girl with a ball",
            director: "Mark Morrison",
            galleryWallColour: new Color(222, 191, 89),
            paintingType: 3
        },
        {
            id: 22,
            antCountRequirement: 8230,
            payment: 11500000,
            letterContents: "I'm the director of the Hazell Gallery, and we're looking to commission some new groundbreaking art pieces.",
            paymentLetterContents: "We could not be happier with your painting, our visitor numbers have already increased since displaying it!",
            paintingContent: "the dolomites at night",
            director: "Robert Esom",
            galleryWallColour: new Color(94, 222, 89),
            paintingType: 4
        },
        {
            id: 23,
            antCountRequirement: 8570,
            payment: 12000000,
            letterContents: "We need some new paintings at Tulker's Gallery, and we simply must have one of yours!",
            paymentLetterContents: "Wow, what an incredible painting! Christmas came early this year",
            paintingContent: "a man looking out to sea",
            director: "Miley Flyrus",
            galleryWallColour: new Color(216, 222, 89),
            paintingType: 4
        },
        {
            id: 24,
            antCountRequirement: 8910,
            payment: 12500000,
            letterContents: "Your paintings are all that anyone can talk about! We'd love to commission a piece for the Amersham Gallery",
            paymentLetterContents: "We are extremely satisfied with the quality and content of the painting that you sent us",
            paintingContent: "a horse disappearing in front of trees",
            director: "William Williams",
            galleryWallColour: new Color(222, 186, 89),
            paintingType: 4
        },
        {
            id: 25,
            antCountRequirement: 9250,
            payment: 13000000,
            letterContents: "Your unique art style is a must-have! Please send one of your many masterpieces to Pink Road Gallery",
            paymentLetterContents: "Glorious, this one will surely gather a stupendous crowd!",
            paintingContent: "dogs playing poker",
            director: "Joanna Johnson",
            galleryWallColour: new Color(89, 222, 154),
            paintingType: 0
        },
        {
            id: 26,
            antCountRequirement: 9590,
            payment: 13500000,
            letterContents: "The prestigious Chinnor Gallery has demanded that I acquire one of your contemporary art works on their behalf, please may I commission a painting?",
            paymentLetterContents: "When your painting arrived it brought a tear to our eyes! We can't thank you enough",
            paintingContent: "a great wave",
            director: "Doris Dewdrop",
            galleryWallColour: new Color(222, 180, 89),
            paintingType: 1
        },
        {
            id: 27,
            antCountRequirement: 9930,
            payment: 14000000,
            letterContents: "Bold, vibrant, brilliant! That's how the Crowell Gallery (who want to commission one of your paintings) describe you!",
            paymentLetterContents: "Your bespoke artwork has arrived, and I must say, BRAVO!",
            paintingContent: "an apple-faced man",
            director: "Quint Blank",
            galleryWallColour: new Color(99, 89, 222),
            paintingType: 2
        },
        {
            id: 28,
            antCountRequirement: 10270,
            payment: 14500000,
            letterContents: "The paintings you create are truly one-of-a-kind! We, the Aston Gallery, must have one!",
            paymentLetterContents: "A true visionary! Such amazing brushwork! It was a pleasure doing business with you",
            paintingContent: "apple pickers",
            director: "Justice Barnett",
            galleryWallColour: new Color(222, 192, 89),
            paintingType: 3
        },
        {
            id: 29,
            antCountRequirement: 10610,
            payment: 15000000,
            letterContents: "There is an empty space at Easington Gallery, which can only be filled by an incredible visionary such as yourself. Please allow us to procure a painting from you!",
            paymentLetterContents: "This is truly a one of a kind piece, consider us more than satisfied!",
            paintingContent: "a bartender",
            director: "Jack Hemblade",
            galleryWallColour: new Color(222, 89, 142),
            paintingType: 4
        },
        {
            id: 30,
            antCountRequirement: 10950,
            payment: 15500000,
            letterContents: "Here at the Chalgrove Gallery we've been blown away by the quality of paintings coming from your studio. We would like to commission a piece for our gallery",
            paymentLetterContents: "Thank you for your wonderful painting. It is just as stunning as I imagined.",
            paintingContent: "a haystack",
            director: "Sierra Spina",
            galleryWallColour: new Color(89, 222, 166),
            paintingType: 0
        },
        {
            id: 31,
            antCountRequirement: 11290,
            payment: 16000000,
            letterContents: "We've been following your work for a while here at the Abingdon Gallery, and we're very impressed! We want to commission a painting.",
            paymentLetterContents: "What an incredible painting! We couldn't have asked for anything better!",
            paintingContent: "some melting clocks",
            director: "Sam Marshall",
            galleryWallColour: new Color(89, 146, 222),
            paintingType: 1
        },
        {
            id: 32,
            antCountRequirement: 11630,
            payment: 16500000,
            letterContents: "I'm the director of the Chamberlin Gallery, and we're looking to commission some new groundbreaking art pieces.",
            paymentLetterContents: "We could not be happier with your painting, our visitor numbers have already increased since displaying it!",
            paintingContent: "a pair of foxes",
            director: "Michaeala Scammels",
            galleryWallColour: new Color(222, 89, 210),
            paintingType: 2
        },
        {
            id: 33,
            antCountRequirement: 11970,
            payment: 17000000,
            letterContents: "We need some new paintings at South Hill Gallery, and we simply must have one of yours!",
            paymentLetterContents: "Wow, what an incredible painting! Christmas came early this year",
            paintingContent: "a man with 4 arms",
            director: "Andrew Lavis",
            galleryWallColour: new Color(89, 205, 222),
            paintingType: 3
        },
        {
            id: 34,
            antCountRequirement: 12310,
            payment: 17500000,
            letterContents: "Your paintings are all that anyone can talk about! We'd love to commission a piece for the Sutton Gallery",
            paymentLetterContents: "We are extremely satisfied with the quality and content of the painting that you sent us",
            paintingContent: "a hare",
            director: "Alasdair Dow",
            galleryWallColour: new Color(178, 222, 89),
            paintingType: 4
        },
        {
            id: 35,
            antCountRequirement: 12650,
            payment: 18000000,
            letterContents: "Your unique art style is a must-have! Please send one of your many masterpieces to Goosey Gallery",
            paymentLetterContents: "Glorious, this one will surely gather a stupendous crowd!",
            paintingContent: "a leaf",
            director: "Katherine English",
            galleryWallColour: new Color(167, 222, 89),
            paintingType: 0
        },
        {
            id: 36,
            antCountRequirement: 12990,
            payment: 18500000,
            letterContents: "The prestigious Challow Gallery has demanded that I acquire one of your contemporary art works on their behalf, please may I commission a painting?",
            paymentLetterContents: "When your painting arrived it brought a tear to our eyes! We can't thank you enough",
            paintingContent: "a mountain scene with a pink sky",
            director: "Oliver Cousins",
            galleryWallColour: new Color(89, 154, 222),
            paintingType: 1
        },
        {
            id: 37,
            antCountRequirement: 13330,
            payment: 19000000,
            letterContents: "Bold, vibrant, brilliant! That's how the Uffington Gallery (who want to commission one of your paintings) describe you!",
            paymentLetterContents: "Your bespoke artwork has arrived, and I must say, BRAVO!",
            paintingContent: "a man made of fruit and veg",
            director: "Matt Pope",
            galleryWallColour: new Color(222, 89, 220),
            paintingType: 2
        },
        {
            id: 38,
            antCountRequirement: 13670,
            payment: 19500000,
            letterContents: "The paintings you create are truly one-of-a-kind! We, the Pinehurst Gallery, must have one!",
            paymentLetterContents: "A true visionary! Such amazing brushwork! It was a pleasure doing business with you",
            paintingContent: "Napolean on a horse",
            director: "Dan Deighton",
            galleryWallColour: new Color(140, 222, 89),
            paintingType: 3
        },
        {
            id: 39,
            antCountRequirement: 14010,
            payment: 20000000,
            letterContents: "There is an empty space at Lydiard Gallery, which can only be filled by an incredible visionary such as yourself. Please allow us to procure a painting from you!",
            paymentLetterContents: "This is truly a one of a kind piece, consider us more than satisfied!",
            paintingContent: "a red room",
            director: "Laura Dickinson",
            galleryWallColour: new Color(222, 171, 89),
            paintingType: 4
        },
        {
            id: 40,
            antCountRequirement: 14350,
            payment: 20500000,
            letterContents: "Here at the Perry Gallery we've been blown away by the quality of paintings coming from your studio. We would like to commission a piece for our gallery",
            paymentLetterContents: "Thank you for your wonderful painting. It is just as stunning as I imagined.",
            paintingContent: "a bridge over water lillies",
            director: "William Lawson",
            galleryWallColour: new Color(126, 222, 89),
            paintingType: 0
        },
        {
            id: 41,
            antCountRequirement: 14690,
            payment: 21000000,
            letterContents: "We've been following your work for a while here at the Bagpath Gallery, and we're very impressed! We want to commission a painting.",
            paymentLetterContents: "What an incredible painting! We couldn't have asked for anything better!",
            paintingContent: "a summer's day in the park",
            director: "Liam Halliday",
            galleryWallColour: new Color(222, 161, 89),
            paintingType: 1
        },
        {
            id: 42,
            antCountRequirement: 15030,
            payment: 21500000,
            letterContents: "I'm the director of the Ozleworth Gallery, and we're looking to commission some new groundbreaking art pieces.",
            paymentLetterContents: "We could not be happier with your painting, our visitor numbers have already increased since displaying it!",
            paintingContent: "a man ice skating",
            director: "Simone Picknett",
            galleryWallColour: new Color(89, 170, 222),
            paintingType: 2
        },
        {
            id: 43,
            antCountRequirement: 15370,
            payment: 22000000,
            letterContents: "We need some new paintings at Draycott Gallery, and we simply must have one of yours!",
            paymentLetterContents: "Wow, what an incredible painting! Christmas came early this year",
            paintingContent: "a rainy street",
            director: "Kay Morrison",
            galleryWallColour: new Color(89, 222, 192),
            paintingType: 3
        },
        {
            id: 44,
            antCountRequirement: 15710,
            payment: 22500000,
            letterContents: "Your paintings are all that anyone can talk about! We'd love to commission a piece for the Abwell Gallery",
            paymentLetterContents: "We are extremely satisfied with the quality and content of the painting that you sent us",
            paintingContent: "a skeleton smoking a cigarette",
            director: "Dan Horvath",
            galleryWallColour: new Color(222, 175, 89),
            paintingType: 4
        },
        {
            id: 45,
            antCountRequirement: 16050,
            payment: 23000000,
            letterContents: "Your unique art style is a must-have! Please send one of your many masterpieces to Yorkley Gallery",
            paymentLetterContents: "Glorious, this one will surely gather a stupendous crowd!",
            paintingContent: "a zebra that pops",
            director: "Sarah Ann",
            galleryWallColour: new Color(89, 169, 222),
            paintingType: 0
        },
        {
            id: 46,
            antCountRequirement: 16390,
            payment: 23500000,
            letterContents: "The prestigious Ashford Gallery has demanded that I acquire one of your contemporary art works on their behalf, please may I commission a painting?",
            paymentLetterContents: "When your painting arrived it brought a tear to our eyes! We can't thank you enough",
            paintingContent: "the tower of babel",
            director: "Connor Cadman",
            galleryWallColour: new Color(89, 222, 138),
            paintingType: 1
        },
        {
            id: 47,
            antCountRequirement: 16730,
            payment: 24000000,
            letterContents: "Bold, vibrant, brilliant! That's how the Norton Gallery (who want to commission one of your paintings) describe you!",
            paymentLetterContents: "Your bespoke artwork has arrived, and I must say, BRAVO!",
            paintingContent: "a woman holding a unicorn",
            director: "Becky King",
            galleryWallColour: new Color(222, 89, 147),
            paintingType: 2
        },
        {
            id: 48,
            antCountRequirement: 17070,
            payment: 24500000,
            letterContents: "The paintings you create are truly one-of-a-kind! We, the Rushton Gallery, must have one!",
            paymentLetterContents: "A true visionary! Such amazing brushwork! It was a pleasure doing business with you",
            paintingContent: "three women in period clothing",
            director: "Holly Bevan",
            galleryWallColour: new Color(137, 222, 89),
            paintingType: 3
        },
        {
            id: 49,
            antCountRequirement: 17410,
            payment: 25000000,
            letterContents: "There is an empty space at Stanwick Gallery, which can only be filled by an incredible visionary such as yourself. Please allow us to procure a painting from you!",
            paymentLetterContents: "This is truly a one of a kind piece, consider us more than satisfied!",
            paintingContent: "a woman sleeping in an orange dress",
            director: "Bradley Pelton",
            galleryWallColour: new Color(89, 222, 149),
            paintingType: 4
        },
    ];

}